###########################################################
### ¡Bienvenido al hermoso Jekyll!
### Este archivo de configuración está destinado a configuraciones que afectan a todo su sitio web. cuando tu por primera vez
### configura tu sitio web, debes revisar todas estas configuraciones y editarlas, pero después
### la configuración inicial no necesitará volver a este archivo con frecuencia.
###########################################################

############################
# --- Opciones requeridas --- #
############################

# Name of website
#title: Fundacón San Vicente Pallotti

# Tu nombre para mostrar en el pie de página
author: FSVP

###############################################
# --- Lista de enlaces en la barra de navegación. --- #
###############################################

navbar-links:
  Inicio: "index"
  Quienes Somos: "quienes-somos" 
  Programas: "programas"
  Galerias: "multimedio"
  Donaciones: "donaciones"
#  Resources:
    #  - Beautiful Jekyll: "https://beautifuljekyll.com"
    #  - Learn markdown: "https://www.markdowntutorial.com/"
 #  Author's home: "https://deanattali.com"

################
# --- Logo --- #
################

# Imagen para mostrar en la barra de navegación: funciona mejor con una imagen cuadrada
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/logo-fsvp-.png"

# De forma predeterminada, la imagen se corta en un círculo. Puede desactivar este comportamiento configurando 'round-avatar: false'
round-avatar: false

# Si desea tener un logotipo de imagen en la esquina superior izquierda en lugar de tener el título del sitio web,
# luego especifica el siguiente parámetro
title-img: "/assets/img/logo-fsvp-0049.png"

#####################################
# --- Footer social media links --- #
#####################################

# Seleccione los enlaces de redes sociales que desea mostrar en el pie de página.
# Puede cambiar el orden en que aparecen en la página cambiando el orden aquí.
# Descomenta los enlaces que deseas mostrar y agrega tu información a cada uno.
social-network-links:
  email: "fundacionsanvicentepallotti52@gmail.com"
#  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: deanattali
#  github: daattali
  twitter: daattali
#  patreon: DeanAttali
  youtube: "@daattali"
#  whatsapp: 15551212

#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code" 
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
# rss-description: This website is a virtual proof that I'm awesome

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: false
  vk: false

# Cómo mostrar el enlace a su sitio web en el pie de página
# Elimina esto si no quieres un enlace en el pie de página
url-pretty: "MyWebsite.com"

# Agregue el título del sitio web al título de cada página.
title-on-all-pages: false

# Longitud de la palabra del extracto: trunca el extracto de cada publicación en la página del feed al número especificado de palabras.
excerpt_length: 50

# Si mostrar o no un extracto de cada publicación del blog en la página del feed
feed_show_excerpt: true

# Si mostrar o no una lista de etiquetas debajo de la vista previa de cada publicación en la página de alimentación
feed_show_tags: true

# Agregar un botón de búsqueda a la barra de navegación
post_search: true

# Agregue un botón en el pie de página para editar la página actual. Solo funciona si tu sitio web está alojado en GitHub
edit_page_button: true

# Permitir que los elementos del submenú (elementos del menú de navegación de segundo nivel) sean más largos que el menú de nivel superior
# Si esta configuración está desactivada, es posible que se corten las palabras largas del submenú.
# Consulte https://github.com/daattali/beautiful-jekyll/issues/765 para comprender el problema que esta configuración puede resolver
navbar-var-length: false

# Las palabras clave para asociar con su sitio web, con fines de SEO
#palabrasclave: "mi,lista,de,palabras clave"

######################################
# --- Colours / background image --- #
######################################

# Personalice los colores de su sitio web. Los valores de color pueden ser cualquier color CSS válido.

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternativamente, la barra de navegación, el pie de página y el fondo de la página se pueden configurar en una imagen
# en lugar de color

navbar-img: "https://images.unsplash.com/photo-1590133836463-60bbb04bbc44?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Sugiera un color para que los navegadores móviles lo utilicen como tema del navegador. Esto sólo es compatible con unos pocos navegadores móviles.
#mobile-theme-col: "#0085A1"

# Para cualquier personalización visual adicional, puede incluir archivos CSS adicionales en cada página de su sitio. Enumere cualquier archivo CSS personalizado aquí
#sitio-css:
#  - "/assets/css/custom-styles.css"

# Si tiene archivos JavaScript comunes que deberían incluirse en cada página, enumerelos aquí
#sitio-js:
#  - "/assets/js/custom-script.js"

#################################
# --- Web Analytics Section --- #
#################################

# Fill in your Google Analytics tag ID (or "Measurement ID") to track your website usage
#gtag: "G-XXXXXXXXXX"

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- deprecated
# As of July 2023 this is no longer supported by Google! If you are still using `google_analytics`,
# you should switch to using the `gtag` field above instead.
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- Comments --- #
####################

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use CommentBox, sign up for a Project ID on https://commentbox.io
#commentbox: "" # Project ID, e.g. "5694267682979840-proj"

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# section commented if you aren't using reCaptcha for spam protection. 
# Using Staticman requires advanced knowledge, please consult 
# https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further 
# instructions. For any support with staticman please direct questions to staticman and 
# not to BeautifulJekyll.
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well) 
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository, 
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below 
# See more details about giscus and each of the following parameters at https://giscus.app
#giscus:
#  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  repository-id: # ID of your repository, retrieve this info from https://giscus.app
#  category: Announcements # Category name of your GitHub Discussion posts
#  category-id: # ID of your category, retrieve this info from https://giscus.app
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

# Formato de fecha Ruby para mostrar fechas de publicaciones
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# ---No necesitas tocar nada debajo aquí (pero puedes hacerlo si quieres) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

